version: "3.8"

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#      - "8055:8080"
      - "8080:8080"
    environment:
#      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
#      - SERVICES=dynamodb,lambda,kinesis,glue
      - LAMBDA_EXECUTOR=docker_reuse
      - DEFAULT_REGION=ap-southeast-2
#      - AWS_PROFILE=localstack
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_DOCKER_NETWORK=localstack-tutorial
      - KINESIS_PROVIDER=kinesalite
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"